### ISSUE TITLE
Please implement a "wide" CSS class for our applications

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/clarity-theme#12]
CSIS uses only part of available screen width. This is especially annoying for the applications that *need* more space, like the EEA viewer:

![image](https://user-images.githubusercontent.com/2961790/66553468-733d9100-eb4b-11e9-9d18-af2b6087482b.png)

At least some other applications would profit from full-width too. The IMO simplest way to allow this while keeping the fixed width  look and feel of the rest of the CSIS would be to provide a "wide" CSS class. 

![image](https://user-images.githubusercontent.com/2961790/66553972-61102280-eb4c-11e9-83ae-fbaa90f4132f.png)

Personally I would not mind the application always taking up 100% of the width. By the way, are we using the sidebars at all? Do we plan to?

**Comment by patrickkaleta** [comment]
> ...By the way, are we using the sidebars at all? Do we plan to?

AFAIK we don't currently use them and there are no concrete plans on using the sidebars in the future, but I think it could still come in handy at some point later on. Maybe we can move our filters and "sort by" elements into separate blocks and place them inside the sidebars. We could show the general study settings in those sidebars while the user is viewing the GL-steps, or we could show the existing report images for the current GL-step/tab combinations, etc etc... so I would leave the sidebars, since they could become valuable to us in the future

**Comment by DenoBeno** [comment]
or we could show the steps in the sidebar, like we do in DRIVER+ pos.

**Comment by p-a-s-c-a-l** [comment]
Please close this issue if this has been resolved in the [updated theme](https://github.com/clarity-h2020/clarity-theme/issues/17) or give feedback on the status.

**Comment by patrickkaleta** [comment]
Not resolved and IMO this should not be implemented. The possible usage of sidebars is more valuable than having the option of showing some apps with full width. If external applications need to be displayed with full width, they should have an option to be displayed in such fashion.
I think we had such a feature for our maps. @therter wasn't there a button for the map application that allowed the users to view the map on full screen? Were there any issues with that or why was it removed?

**Comment by therter** [comment]
> wasn't there a button for the map application that allowed the users to view the map on full screen? Were there any issues with that or why was it removed?

Yes, this plugin caused some problems with other features.

**Comment by patrickkaleta** [comment]
> > wasn't there a button for the map application that allowed the users to view the map on full screen? Were there any issues with that or why was it removed?
> 
> Yes, this plugin caused some problems with other features.

Ok, too bad. Still I'm going to close this issue for now, since I don't see an urgent need for this ATM.
