### ISSUE TITLE
Improve overall appearance of our forms

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/clarity-theme#13]
We will have to work on the styling of our forms to make them more user-friendly. In general we have some quite complex forms (e.g. for data packages, resources, Solution offers,...) and it's not always easy to figure out which fields are important to fill out or which fields belong to the actual content being created or to some other content that is just being referenced (or being created inline as a reference).

@DanielRodera and @bullz: I don't have any concrete ideas yet, so maybe we could go over a couple of these forms and discuss them in a separate telco. WDYT?

**Comment by DanielRodera** [comment]
Hi @patrickkaleta,

Sure, I will contact Alejandro and I will propose a slot for next week,

I will let you know,

Cheers

**Comment by patrickkaleta** [comment]
related to #8

**Comment by p-a-s-c-a-l** [comment]
Please close this issue if this has been resolved in the [updated theme](https://github.com/clarity-h2020/clarity-theme/issues/17) or give feedback on the status.

**Comment by patrickkaleta** [comment]
IMO the forms have improved and it's now easier to recognize which fields belong to what. Obviously, there's still room for improvement, but I'll close this issue now until we get some concrete feedback/improvement wishes from users.
