### ISSUE TITLE
Overall minor CSS bugs

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/clarity-theme#15]
### This issue collects all minor bugs in the current theme.

- [x] "add member" form - suggestions list is missing a background

- [ ] tbd...

**Comment by patrickkaleta** [comment]
### "add member" form Bug

When you start typing a name, a list of suggested users appear beneath the input, but this list has no background, so it's not readable.

![add-users-css-bug](https://user-images.githubusercontent.com/42167036/69954942-da007a80-14fc-11ea-8e72-daef7b5df82b.png)

**Fix:**
add a border and background property to the `.ui-autocomplete` class.

**Comment by p-a-s-c-a-l** [comment]
Please close this issue if this has been resolved in the [updated theme](https://github.com/clarity-h2020/clarity-theme/issues/17) or give feedback on the status.

**Comment by patrickkaleta** [comment]
"Add member" form error now fixed. Leaving this issue open in case we encounter any other/new minor bugs with the theme update.

**Comment by p-a-s-c-a-l** [comment]
> in case we encounter any other/new minor bugs with the theme update.

Doesn't seem so. :-)
If something breaks, we can open a new issue.
