### ISSUE TITLE
Show Study titles on page

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/clarity-theme#16]
Add the Study titles on top of the navigation, so that users know what Study they are currently viewing. Otherwise users with multiple studies will have problems knowing which of their studies they are currently working with.

I've already created two View blocks (one for Group-page, one for the Node-pages) that display the title ([for group](https://csis.myclimateservice.eu/admin/structure/views/view/study_group_overview/edit/block_2), [for node](https://csis.myclimateservice.eu/admin/structure/views/view/view_mode_for_gl_step/edit/block_1)) and added a `study-title` class to the view to make styling with CSS easier. I added them to the "Title Heading" region in the Block layout, but disabled them for now, since they first need proper styling.

@bullz 
Miguel informed me that you are currently working on a new version of the theme, so could you please also take care of the titles in the Study? I had something like this in mind, but do however you feel it is best:
![study-title on screen](https://user-images.githubusercontent.com/42167036/73532423-f2b5df80-441c-11ea-8a2b-ddb8f8c1ca85.png)

**Comment by p-a-s-c-a-l** [comment]
Please close this issue if this has been resolved in the [updated theme](https://github.com/clarity-h2020/clarity-theme/issues/17) or give feedback on the status.

**Comment by patrickkaleta** [comment]
It has been resolved. I made just some [small adjustments](https://github.com/clarity-h2020/clarity-theme/commit/088d0d1e391d5841a0520f4c971ad6e6fd792fb3) in the theme and updated the 2 views.
