### ISSUE TITLE
Scenario Analysis app not working properly due to missing seamless.js

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/clarity-theme#2]
Scenario analysis app is not displayed properly.
![theme-bug-1](https://user-images.githubusercontent.com/42167036/63274591-55b51f00-c2a0-11e9-969a-edd2c874a653.png)

Probably just caused by a missing seamless.js, which was not properly added to the new theme.

After including the `clarity/global-scripts` in the [clarity.info.yml](https://github.com/clarity-h2020/clarity-theme/blob/dev/clarity.info.yml), all additional js files are now included in the theme and working as expected.

**Comment by p-a-s-c-a-l** [comment]
Perhaps the theme is not the best place? seamless.js is only needed on those pages that inlcude external apps via iFrame **and only** when those apps are initialised via seamless.js. Currently this is the case for the MCDA App.

**Comment by patrickkaleta** [comment]
Then perhaps we could move it into the csis helpers module and include it just where it's needed (just like it's the case with the html2canvas.js necessary for taking report image screenshots).

@fgeyer16: any objections to moving the seamless.js from the theme into our custom module?

**Comment by fgeyer16** [comment]
> any objections to moving the seamless.js from the theme into our custom module?

No  o objectives. In contrary, since this is functionality it should be in a module and not in a theme.

**Comment by patrickkaleta** [comment]
Done. Seamless.js is now inside the csis helpers module and currently loaded just for GL-steps, since they are the only entity type, where the MCDA app is available.
