### ISSUE TITLE
Grouping fields as horizontal tabs not working

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/clarity-theme#3]
When grouping fields together and displaying them as horizontal tabs (e.g. the case for the Mock-Up in the [Maps tab](https://csis.myclimateservice.eu/study/1/step/2/view/maps)), the Mock-Up is displayed as open by default (when it shouldn't) and it won't collapse.
![theme-bug-2](https://user-images.githubusercontent.com/42167036/63278800-3fab5c80-c2a8-11e9-93cb-ba306000c4e5.png)

When using another display setting (e.g. "vertical tabs" or "details"), it is displayed properly. Horizontal tabs work with the old csis theme, so I don't think it's an issue with the [Field Group](https://www.drupal.org/project/field_group) module.

@fgeyer16, @bullz any idea what's causing this problem?

**Comment by fgeyer16** [comment]
The Display settings where somehow strange. The analysis map element fas set to fieldset and outside the horizontal tabs element. Changed type from fieldset to tab and moved it into the horizontal tabs group. Now it seems to work.

Or did you intend something else?

**Comment by patrickkaleta** [comment]
> The Display settings where somehow strange. The analysis map element fas set to fieldset and outside the horizontal tabs element. Changed type from fieldset to tab and moved it into the horizontal tabs group. Now it seems to work.
> 
> Or did you intend something else?

No this is okay. At some point we will probably (hopefully) be able to remove the Mock-up tabs, so this won't be even necessary anymore. I was just worried that non-working horizontal tabs might cause us trouble in other places than the Study.

I will make sure that we have the same way of visualizing the Mock-ups in all the steps/tabs.
