### ISSUE TITLE
Header region not wide enough for current navigation links

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/clarity-theme#5]
E.g. "Solution offers" are now displayed on two rows and when it is the active tab, then the underlining doesn't match.
![theme-bug-4](https://user-images.githubusercontent.com/42167036/63280470-20fa9500-c2ab-11e9-9403-d0ce08761f81.png)

I think, we could simply allow the **Header** region to be wider and not be limited by the width of the **Content** region. Or we could move the "User account menu" (My account & Log out) some place else other than the Header.

**Comment by bullz** [comment]
This issue was solved by moving **user account** menu
