### ISSUE TITLE
Need better styling of datapackage and resource forms

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/clarity-theme#8]
The current theme is not so great for when the user tries to edit/create resources or data packages. Main problem IMO is that we need better separation between the actual entity that is being edited and any potential referenced entities, which can be edited inline. See for e.g. this screenshot:
![styling of forms](https://user-images.githubusercontent.com/42167036/64252123-598ca680-cf1a-11e9-9486-a50b631ae93a.png)

There I'm editing this [datapackage](https://csis.myclimateservice.eu/node/733/edit/simplifieddatapackage) and wanted to edit an entry in the "Other sources" field. This opens an inline form and I cannot tell where this inline form starts and where it ends (I highlighted it with the Browser console). Since there are so many fields in these forms, it gets quite confusing even for someone who modelled the data structure of this thing.

Inline entity form opens those inline forms in a `tr` element with class "ief-row-form", one idea would be to maybe change the padding and background of those elements to make them "pop out" of the original form.

**Comment by patrickkaleta** [comment]
@bullz following up on our telco from 1-2 weeks ago, how is the status here? have you been able to make those forms a little more user-friendly?

**Comment by p-a-s-c-a-l** [comment]
Please close this issue if this has been resolved in the [updated theme](https://github.com/clarity-h2020/clarity-theme/issues/17) or give feedback on the status.

**Comment by patrickkaleta** [comment]
Adressed in this [commit](https://github.com/clarity-h2020/clarity-theme/commit/336c3af3abd9de5625bc6bbd5d4baf1ab5d5742c)
For the inline forms showing up in our data package forms (in the Resources/Datasets field) I added an alternating coloring of the items for odd/even elements (just like we have it in other places) and I gave the entity which is being edited directly inside the DP a slighty darker background and a border. 

IMO this is now good enough, so I'm closing this issue.
